### ISSUE TITLE
Application of PheWAS-cluster Methods to Different Resources and Populations

### ISSUE THREAD

**Issue by laleoarrow** [LizaDarrous/PheWAS-cluster#1]
Hi! Impressive work! Congrats on your publication in _NC_! I'm very interested in your methods for PheWAS. I have a few questions: Can this method also be applied to other potential PheWAS resources such as IEU (https://gwas.mrcieu.ac.uk/phewas/) or other non-EUR population background traits (e.g., BBJ)? If it can, does it require additional adjustments?  Thank you!

**Comment by LizaDarrous** [comment]
Hello, thank you for your interest in our method! 
Indeed, the user is encouraged to use PheWAS resources such as the MRC IEU website you linked. Our lab had local UKB summary stat data (from Neale's lab) curated over years of research so I created my PheWAS data-frame in-house by going into each phenotype file and extracting the SNP associations I needed, but there are different ways online instead. 
As for the ancestry/population background of traits, I cannot give a definitive answer but there is some evidence that genetic effects on traits are similar across (local) ancestries, so I tentatively say that it can be used without additional adjustments. 

Thanks again for your message, I will close this 'issue' in two days time :)

**Comment by laleoarrow** [comment]
Thank you for clarifying this!
